cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

menu/urls.py
from django.urls import path

from . import views
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', main),

    path('form/', views.product_list, name='product_list'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('suveniru/', views.suveniru_list, name='suveniru_list'),
    path('<int:id>/<slug:slug>/', views.suveniru_list, name='suveniru_detail'),
    path('specials/', views.specials_list, name='specials_list'),
    path('<int:id>/<slug:slug>/', views.specials_detail, name='specials_detail'),
    path('contact/', views.contact_list, name='contact_list'),
    path('<int:id>/<slug:slug>/', views.contact_detail, name='contact_detail'),

]

sport/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
    # path('form/', include('menu.urls')),
    # path('suveniru/', include('menu.urls')),

    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

menu/views.py
from django.shortcuts import get_object_or_404, render

from cart.cart import Cart
from shop.models import Product, Suveniru, Specials, Contact


def product_list(request, category_slug=None):
    cart = Cart(request)
    products = Product.objects.filter(available=True)
    return render(request, 'form.html', {'products': products, 'cart': cart})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request,
                  'product_detail.html',
                  {'product': product}
                  )

def suveniru_list(request, category_slug=None):
    cart = Cart(request)
    suvenirus = Suveniru.objects.filter(available=True)
    return render(request, 'suveniru.html', {'suvenirus': suvenirus, 'cart': cart})


def suveniru_detail(request, id, slug):
    suveniru = get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request,
                  'suveniru_detail.html',
                  {'suveniru': suveniru}
                  )

def main(request):
    return render(request, 'main.html')

def specials_list(request, category_slug=None):
    cart = Cart(request)
    specialss = Specials.objects.filter(available=True)
    return render(request, 'specials.html', {'specialss': specialss, 'cart': cart})


def specials_detail(request, id, slug):
    specials = get_object_or_404(Specials, id=id, slug=slug, available=True)
    return render(request,
                  'specials-detail.html',
                  {'specials': specials}
                  )

def contact_list(request, category_slug=None):
    contacts = Contact.objects.filter(available=True)
    return render(request, 'contact.html', {'contacts': contacts})


def contact_detail(request, id, slug):
    contact = get_object_or_404(Specials, id=id, slug=slug, available=True)
    return render(request,
                  'contact-detail.html',
                  {'contact': contact}
                  )

menu/templates/contact-detail.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
    {{ contact.adress }}
{% endblock %}

{% block con %}
    <div class="contact-detail">
        <h1>{{ contact.tel }} {{ contact.adress }}</h1>

    </div>
{% endblock %}

menu/templates/contact.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
    Contact
{% endblock %}
{% block con %}
    <div id="main" class="contact-list">
        <h1>contacts</h1>
        {% for contact in contacts %}
            <div class="item">
                <a href="{{ contact.get_absolute_url }}">{{ contact.tel }}</a>
                <br>
                {{ contact.adress }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

menu/templates/form.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
    Form
{% endblock %}

{% block content %}
    <div id="main" class="product-list">
        <h1>Products</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                <br>
                &#8372; {{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

menu/templates/product_detail.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>

        <p class="price">${{ product.price }}</p>
        <a href="{% url "cart:cart_add" product.id %}">Add to cart</a>

        {{ product.description|linebreaks }}
    </div>
{% endblock %}

menu/templates/specials-detail.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
    {{ specials.name }}
{% endblock %}

{% block spe %}
    <div class="specials-detail">
        <img src="{% if specials.image %}{{ specials.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ specials.name }}</h1>

        <p class="price">${{ specials.price }}</p>
        <a href="{% url "cart:cart_add" specials.id %}">Add to cart</a>

        {{ specials.description|linebreaks }}
    </div>
{% endblock %}

menu/templates/specials.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
    Specials
{% endblock %}
{% block spe %}
    <div id="main" class="specials-list">
        <h1>specialss</h1>
        {% for specials in specialss %}
            <div class="item">
                <a href="{{ specials.get_absolute_url }}">
                    <img src="{% if specials.image %}{{ specials.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
                <a href="{{ specials.get_absolute_url }}">{{ specials.name }}</a>
                <br>
                &#8372; {{ specials.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

menu/templates/suveniru.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
    Suveniru
{% endblock %}
{% block suv %}
    <div id="main" class="suveniru-list">
        <h1>suvenirus</h1>
        {% for suveniru in suvenirus %}
            <div class="item">
                <a href="{{ suveniru.get_absolute_url }}">
                    <img src="{% if suveniru.image %}{{ suveniru.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
                <a href="{{ suveniru.get_absolute_url }}">{{ suveniru.name }}</a>
                <br>
                &#8372; {{ suveniru.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

menu/templates/suveniru_detail.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
    {{ suveniru.name }}
{% endblock %}

{% block suv %}
    <div class="suveniru-detail">
        <img src="{% if suveniru.image %}{{ suveniru.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ suveniru.name }}</h1>

        <p class="price">${{ suveniru.price }}</p>
        <a href="{% url "cart:cart_add" suveniru.id %}">Add to cart</a>

        {{ suveniru.description|linebreaks }}
    </div>
{% endblock %}